# This task builds and loads VXLAN configuration to all switches
- name: Build VXLAN interfaces and deploy configuration
  hosts: vqfx10k
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Build configuration
      template: src=vqfx.vxlan.conf.j2 dest=/tmp/vxlan_{{ inventory_hostname }}.conf
    - name: Deploy VXLAN config to device ... please wait
      junos_install_config:
        host: "{{ ansible_ssh_host }}"
        port: "{{ ansible_ssh_port }}"
        user: root
        passwd: Juniper
        file: "/tmp/vxlan_{{ inventory_hostname }}.conf"
        overwrite: no
        replace: no
        logfile: /tmp/changes.log
